# Generated by Django 5.1.6 on 2025-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=63)),
                ('vendorname', models.CharField(max_length=63)),
                ('username', models.CharField(max_length=63)),
                ('password', models.CharField(max_length=63)),
                ('address', models.CharField(max_length=63)),
                ('phonenumber', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('igst', models.CharField(max_length=63)),
            ],
        ),
    ]
