# Generated by Django 5.1.6 on 2025-02-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='phonenumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
