# Generated by Django 5.1.6 on 2025-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('gst_doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('bank_details', models.TextField()),
            ],
        ),
    ]
