# Generated by Django 5.1.6 on 2025-02-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0002_uploaddocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='bank_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
