# Generated by Django 5.1.6 on 2025-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0003_alter_uploaddocuments_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='username',
            field=models.CharField(max_length=63, unique='true'),
        ),
    ]
