# Generated by Django 5.1.6 on 2025-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0004_rfq_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CFOUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
    ]
