# Generated by Django 5.1.6 on 2025-02-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0004_alter_vendordetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='bank_details',
            field=models.CharField(max_length=255),
        ),
    ]
