# Generated by Django 5.1.6 on 2025-02-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0005_alter_uploaddocuments_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='bank_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
