# Generated by Django 5.1.6 on 2025-02-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0005_ceouser_cfouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Material', 'Material'), ('Service', 'Service')], max_length=50)),
                ('item_description', models.TextField()),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved by CFO', 'Approved by CFO'), ('Approved by CEO', 'Approved by CEO'), ('Rejected by CFO', 'Rejected by CFO'), ('Rejected by CEO', 'Rejected by CEO')], default='Pending', max_length=50)),
                ('next_approver', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
