# Generated by Django 5.1.6 on 2025-02-20 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0006_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='modification_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 20, 17, 34, 10)),
            preserve_default=False,
        ),
    ]
