# Generated by Django 5.1.6 on 2025-02-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0006_alter_uploaddocuments_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='bank_details',
            field=models.CharField(blank=True, default='Default Value', max_length=63),
        ),
    ]
