# Generated by Django 5.1.6 on 2025-02-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0007_requirement_modification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='quotation_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
