# Generated by Django 5.1.6 on 2025-02-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acgl', '0009_designheaduser_financeheaduser_hoduser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='RFQ',
        ),
    ]
