# Generated by Django 5.1.6 on 2025-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0011_vendorbankanddocuments_vendorpersonaldetails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorbankanddocuments",
            name="vendor_code",
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
