# Generated by Django 5.1.6 on 2025-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0012_vendorbankanddocuments_vendor_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorbankanddocuments",
            name="id",
        ),
        migrations.AlterField(
            model_name="vendorbankanddocuments",
            name="aadhar_doc",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="vendorbankanddocuments",
            name="bank_doc",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="vendorbankanddocuments",
            name="gst_doc",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="vendorbankanddocuments",
            name="pan_doc",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="vendorbankanddocuments",
            name="vendor_code",
            field=models.CharField(
                blank=True, max_length=5, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
