# Generated by Django 5.1.6 on 2025-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0013_remove_vendorbankanddocuments_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="delivery_address",
            field=models.CharField(
                blank=True, default="Pune", max_length=255, null=True
            ),
        ),
    ]
