# Generated by Django 5.1.6 on 2025-02-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0014_requirement_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="rfq_no",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
