# Generated by Django 5.1.6 on 2025-02-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0015_requirement_rfq_no_alter_requirement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirement",
            name="rfq_no",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
