# Generated by Django 5.1.6 on 2025-02-23 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0016_alter_requirement_rfq_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFQResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                ("response_deadline", models.DateTimeField()),
                ("company_name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("item_number", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("specification", models.TextField()),
                (
                    "per_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity", models.IntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("gst", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gst_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="rfq_attachments/"
                    ),
                ),
                (
                    "rfq_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acgl.requirement",
                    ),
                ),
            ],
        ),
    ]
