# Generated by Django 5.1.6 on 2025-02-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0017_rfqresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfqresponse",
            name="rfq_number",
            field=models.CharField(max_length=50),
        ),
    ]
