# Generated by Django 5.1.6 on 2025-02-23 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0018_alter_rfqresponse_rfq_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqresponse",
            name="vendor_code",
            field=models.ForeignKey(
                default=10190,
                on_delete=django.db.models.deletion.CASCADE,
                to="acgl.vendorbankanddocuments",
            ),
            preserve_default=False,
        ),
    ]
