# Generated by Django 5.1.6 on 2025-02-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0019_rfqresponse_vendor_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckboxState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfq_number", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
                ("is_checked", models.BooleanField(default=False)),
            ],
        ),
    ]
