# Generated by Django 5.1.6 on 2025-02-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0020_checkboxstate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CheckboxState",
        ),
    ]
