# Generated by Django 5.1.6 on 2025-02-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0021_delete_checkboxstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqresponse",
            name="design_head_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rfqresponse",
            name="finance_head_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rfqresponse",
            name="hod_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rfqresponse",
            name="quality_head_verification",
            field=models.BooleanField(default=False),
        ),
    ]
