# Generated by Django 5.1.6 on 2025-02-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0022_rfqresponse_design_head_verification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceNegotiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "negotiated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("admin_comments", models.TextField(blank=True, null=True)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("vendor_comments", models.TextField(blank=True, null=True)),
                (
                    "rfq_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acgl.rfqresponse",
                    ),
                ),
            ],
        ),
    ]
