# Generated by Django 5.1.6 on 2025-02-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0023_pricenegotiation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceNegotiation",
        ),
    ]
