# Generated by Django 5.1.6 on 2025-02-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0024_delete_pricenegotiation"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqresponse",
            name="admin_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqresponse",
            name="negotiation_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
