# Generated by Django 5.1.6 on 2025-02-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0025_rfqresponse_admin_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfqresponse",
            name="negotiation_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name="rfqresponse",
            unique_together={("rfq_number", "vendor_code")},
        ),
    ]
