# Generated by Django 5.1.6 on 2025-02-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0026_alter_rfqresponse_negotiation_amount_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rfqresponse",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="rfqresponse",
            name="admin_comments",
        ),
        migrations.RemoveField(
            model_name="rfqresponse",
            name="negotiation_amount",
        ),
    ]
