# Generated by Django 5.1.6 on 2025-02-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0027_alter_rfqresponse_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqresponse",
            name="final_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="rfqresponse",
            name="negotiated_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="rfqresponse",
            name="negotiation_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
