# Generated by Django 5.1.6 on 2025-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acgl", "0028_rfqresponse_final_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqresponse",
            name="negotiation_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rfqresponse",
            name="vendor_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqresponse",
            name="vendor_counter_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
